In [1]:
import torch

# Floating point types
float16 = torch.tensor([1, 2, 3], dtype=torch.float16)    # Half precision
float32 = torch.tensor([1, 2, 3], dtype=torch.float32)    # Single precision (DEFAULT)
float64 = torch.tensor([1, 2, 3], dtype=torch.float64)    # Double precision
bfloat16 = torch.tensor([1, 2, 3], dtype=torch.bfloat16)  # Brain float

# Integer types
int8 = torch.tensor([1, 2, 3], dtype=torch.int8)          # 8-bit integer
int16 = torch.tensor([1, 2, 3], dtype=torch.int16)        # 16-bit integer
int32 = torch.tensor([1, 2, 3], dtype=torch.int32)        # 32-bit integer
int64 = torch.tensor([1, 2, 3], dtype=torch.int64)        # 64-bit integer (DEFAULT)

# Other types
bool_type = torch.tensor([True, False], dtype=torch.bool) # Boolean
uint8 = torch.tensor([1, 2, 3], dtype=torch.uint8)        # Unsigned 8-bit integer

print("Float32 size:", float32.element_size(), "bytes")
print("Float64 size:", float64.element_size(), "bytes")
print("Int64 size:", int64.element_size(), "bytes")

Float32 size: 4 bytes
Float64 size: 8 bytes
Int64 size: 8 bytes


In [2]:
import torch

tensor0d = torch.tensor(1)                   # 0D tensor (scalar)
tensor1d = torch.tensor([1, 2, 3])           # 1D tensor (vector)
tensor2d = torch.tensor([[1, 2],
                         [3, 4]])            # 2D tensor (matrix)
tensor3d = torch.tensor([[[1, 2], [3, 4]],
                         [[5, 6], [7, 8]]])  # 3D tensor

print("0D tensor: \n", tensor0d)
print("\n1D tensor: \n", tensor1d)
print("\n2D tensor: \n", tensor2d)
print("\n3D tensor: \n", tensor3d)


0D tensor: 
 tensor(1)

1D tensor: 
 tensor([1, 2, 3])

2D tensor: 
 tensor([[1, 2],
        [3, 4]])

3D tensor: 
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [3]:
import torch

# Method 1: Using dtype parameter
float_tensor1 = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
float_tensor2 = torch.tensor([1.5, 2.7, 3.9], dtype=torch.float64)

print("Float32 tensor:", float_tensor1, float_tensor1.dtype)
print("Float64 tensor:", float_tensor2, float_tensor2.dtype)

Float32 tensor: tensor([1., 2., 3., 4.]) torch.float32
Float64 tensor: tensor([1.5000, 2.7000, 3.9000], dtype=torch.float64) torch.float64


In [4]:
# PyTorch automatically infers float32 from Python floats
auto_float = torch.tensor([1.0, 2.0, 3.0])  # Automatically float32
mixed = torch.tensor([1, 2.5, 3])           # Mixed -> promotes to float32

print("Auto float:", auto_float.dtype)      # torch.float32
print("Mixed types:", mixed.dtype)          # torch.float32

Auto float: torch.float32
Mixed types: torch.float32


In [5]:
import torch

# Example 1: 1D Tensor (Vector)
vector = torch.tensor([1, 2, 3, 4, 5])
print("=== 1D Tensor ===")
print("Tensor:", vector)
print("Shape:", vector.shape)                 # torch.Size([5])
print("Rank:", vector.dim())                  # 1
print("Size:", vector.size())                 # torch.Size([5])
print("Number of elements:", vector.numel())  # 5
print("Data type: ", vector.dtype)            # torch.int64
print("Device: ", vector.device)              # cpu


# Example 2: 2D Tensor (Matrix)
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\n=== 2D Tensor ===")
print("Tensor:", matrix)
print("Shape:", matrix.shape)                # torch.Size([2, 3])
print("Rank:", matrix.dim())                 # 2
print("Size:", matrix.size())                # torch.Size([2, 3])
print("Number of elements:", matrix.numel()) # 6
print("Data type: ", matrix.dtype)           # torch.int64
print("Device: ", matrix.device)              # cpu

# Example 3: 3D Tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n=== 3D Tensor ===")
print("Tensor:", tensor_3d)
print("Shape:", tensor_3d.shape)                # torch.Size([2, 2, 2])
print("Rank:", tensor_3d.dim())                 # 3
print("Size:", tensor_3d.size())                # torch.Size([2, 2, 2])
print("Number of elements:", tensor_3d.numel()) # 8
print("Data type: ", tensor_3d.dtype)              # torch.int64
print("Device: ", tensor_3d.device)              # cpu

=== 1D Tensor ===
Tensor: tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
Rank: 1
Size: torch.Size([5])
Number of elements: 5
Data type:  torch.int64
Device:  cpu

=== 2D Tensor ===
Tensor: tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Rank: 2
Size: torch.Size([2, 3])
Number of elements: 6
Data type:  torch.int64
Device:  cpu

=== 3D Tensor ===
Tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])
Rank: 3
Size: torch.Size([2, 2, 2])
Number of elements: 8
Data type:  torch.int64
Device:  cpu


In [6]:
import torch

# 1D tensor
vector = torch.tensor([10, 20, 30, 40, 50])
print("Original vector:", vector)

# Access single element
print("vector[2]:", vector[2])        # tensor(30)
print("vector[-1]:", vector[-1])      # tensor(50) - last element

# Access range of elements (slicing)
print("vector[1:4]:", vector[1:4])    # tensor([20, 30, 40])
print("vector[:3]:", vector[:3])      # tensor([10, 20, 30]) - first 3
print("vector[2:]:", vector[2:])      # tensor([30, 40, 50]) - from index 2

Original vector: tensor([10, 20, 30, 40, 50])
vector[2]: tensor(30)
vector[-1]: tensor(50)
vector[1:4]: tensor([20, 30, 40])
vector[:3]: tensor([10, 20, 30])
vector[2:]: tensor([30, 40, 50])


In [7]:
# 2D tensor (matrix)
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
print("Original matrix:")
print(matrix)

# Access single element
print("matrix[0, 1]:", matrix[0, 1])      # tensor(2) - row 0, column 1
print("matrix[2, 0]:", matrix[2, 0])      # tensor(7) - row 2, column 0

# Access entire row
print("matrix[1]:", matrix[1])            # tensor([4, 5, 6]) - row 1
print("matrix[1, :]:", matrix[1, :])      # Same as above

# Access entire column
print("matrix[:, 2]:", matrix[:, 2])      # tensor([3, 6, 9]) - column 2

Original matrix:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
matrix[0, 1]: tensor(2)
matrix[2, 0]: tensor(7)
matrix[1]: tensor([4, 5, 6])
matrix[1, :]: tensor([4, 5, 6])
matrix[:, 2]: tensor([3, 6, 9])


In [8]:
# 3D tensor (batch, rows, columns)
tensor_3d = torch.tensor([[[1, 2], [3, 4]],
                          [[5, 6], [7, 8]],
                          [[9, 10], [11, 12]]])
print("3D tensor shape:", tensor_3d.shape)          # torch.Size([3, 2, 2])

# Access different dimensions
print("First batch:", tensor_3d[0])                 # tensor([[1, 2], [3, 4]])
print("Second batch, first row:", tensor_3d[1, 0])  # tensor([5, 6])
print("All batches, first row:", tensor_3d[:, 0])   # tensor([[1, 2], [5, 6], [9, 10]])
print("Specific element:", tensor_3d[2, 1, 0])      # tensor(11)

3D tensor shape: torch.Size([3, 2, 2])
First batch: tensor([[1, 2],
        [3, 4]])
Second batch, first row: tensor([5, 6])
All batches, first row: tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])
Specific element: tensor(11)


In [9]:
# Create a tensor
data = torch.tensor([5, 12, 8, 3, 15, 1])

# Boolean masking
mask = data > 7
print("Mask:", mask)                            # tensor([False, True, True, False, True, False])
print("Values > 7:", data[mask])                # tensor([12, 8, 15])

# Multiple conditions
mask2 = (data > 5) & (data < 10)
print("Values between 5 and 10:", data[mask2])  # tensor([8])

# Direct condition
print("Even numbers:", data[data % 2 == 0])     # tensor([12, 8])

Mask: tensor([False,  True,  True, False,  True, False])
Values > 7: tensor([12,  8, 15])
Values between 5 and 10: tensor([8])
Even numbers: tensor([12,  8])


In [10]:
tensor = torch.tensor([[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]])

# Select specific indices
print("Rows [0, 2], all columns:", tensor[[0, 2]])      # Rows 0 and 2, all columns
print("Columns [1, 2] of all rows:", tensor[:, [1, 2]]) # All rows, columns 1 and 2

# Advanced indexing - select specific elements
rows = torch.tensor([0, 1, 2])
cols = torch.tensor([1, 0, 2])

# From row o, select column 1 and From row 1, select column 0 and From row 2, select column 2
print("Specific elements:", tensor[rows, cols])         # [20, 40, 90]

Rows [0, 2], all columns: tensor([[10, 20, 30],
        [70, 80, 90]])
Columns [1, 2] of all rows: tensor([[20, 30],
        [50, 60],
        [80, 90]])
Specific elements: tensor([20, 40, 90])


In [11]:
import torch

# Create a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
print("Original tensor:")
print(tensor)

# Modify single element
tensor[0, 1] = 99
print("\nAfter modifying [0,1]:")
print(tensor)
# Output:
# [[1, 99, 3],
#  [4,  5, 6],
#  [7,  8, 9]]

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

After modifying [0,1]:
tensor([[ 1, 99,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])


In [12]:
# Modify entire row
tensor[1] = torch.tensor([10, 20, 30])
print("\nAfter modifying row 1:")
print(tensor)

# Modify entire column
tensor[:, 2] = torch.tensor([100, 200, 300])
print("\nAfter modifying column 2:")
print(tensor)

# Modify entire column with a unique number
tensor[:, 1] = torch.tensor(-1)
print("\nAfter modifying column 1:")
print(tensor)


After modifying row 1:
tensor([[ 1, 99,  3],
        [10, 20, 30],
        [ 7,  8,  9]])

After modifying column 2:
tensor([[  1,  99, 100],
        [ 10,  20, 200],
        [  7,   8, 300]])

After modifying column 1:
tensor([[  1,  -1, 100],
        [ 10,  -1, 200],
        [  7,  -1, 300]])


In [13]:
# Create new tensor
tensor = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])

# Modify a slice
tensor[0:2, 1:3] = torch.tensor([[20, 30], [60, 70]])
print("After slice modification:")
print(tensor)

After slice modification:
tensor([[ 1, 20, 30,  4],
        [ 5, 60, 70,  8],
        [ 9, 10, 11, 12]])


In [14]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Modify elements based on condition
print("\n============ Modify elements based on condition ==========\n")
mask = tensor > 5
tensor[mask] = -100
print("After setting values > 5 to 0:")
print(tensor)

print("\n================= Multiple conditions ==============\n")
# Multiple conditions
tensor[(tensor > 1) & (tensor < 4)] = 0
print("After multiple conditions:")
print(tensor)


============ Modify elements based on condition ==========

After setting values > 5 to 0:
tensor([[   1,    2,    3],
        [   4,    5, -100],
        [-100, -100, -100]])

================= Multiple conditions ==============

After multiple conditions:
tensor([[   1,    0,    0],
        [   4,    5, -100],
        [-100, -100, -100]])


In [15]:
tensor = torch.tensor([[1.0, 2.0], 
                       [3.0, 4.0]])

# In-place arithmetic operations
tensor.add_(5)           # Add 5 to all elements (in-place)
print("After add_(5):")
print(tensor)

tensor.mul_(2)           # Multiply all elements by 2 (in-place)
print("\n After mul_(2):")
print(tensor)

# Other in-place operations
tensor.sub_(1)                      # Subtract 1
print("\n After sub_(1): \n", tensor)
tensor.div_(2)                      # Divide by 2
print("\n After div_(2): \n", tensor)
tensor.pow_(2)                      # Square all elements
print("\n After pow_(2): \n", tensor)

After add_(5):
tensor([[6., 7.],
        [8., 9.]])

 After mul_(2):
tensor([[12., 14.],
        [16., 18.]])

 After sub_(1): 
 tensor([[11., 13.],
        [15., 17.]])

 After div_(2): 
 tensor([[5.5000, 6.5000],
        [7.5000, 8.5000]])

 After pow_(2): 
 tensor([[30.2500, 42.2500],
        [56.2500, 72.2500]])


In [16]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Replace values based on condition
modified = torch.where(tensor > 5, 
                      torch.tensor(-10),  # Values where condition is True
                      tensor)            # Values where condition is False
print("Using torch.where():")
print(modified)

Using torch.where():
tensor([[  1,   2,   3],
        [  4,   5, -10],
        [-10, -10, -10]])


In [17]:
tensor = torch.tensor([[1.0, 4.0],
                       [9.0, 16.0]])

# Apply mathematical functions (create new tensors)
sqrt_tensor = torch.sqrt(tensor)          # Square root
log_tensor = torch.log(tensor)            # Natural log
exp_tensor = torch.exp(tensor)            # Exponential

print("\n Square root:\n", sqrt_tensor)
print("\n Log:\n", log_tensor)
print("\n Exponential:\n", exp_tensor)


 Square root:
 tensor([[1., 2.],
        [3., 4.]])

 Log:
 tensor([[0.0000, 1.3863],
        [2.1972, 2.7726]])

 Exponential:
 tensor([[2.7183e+00, 5.4598e+01],
        [8.1031e+03, 8.8861e+06]])


In [18]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]])

# Fill with specific value
tensor.fill_(-5)
print("After fill_(0):")
print(tensor)

# Fill diagonal
tensor.fill_diagonal_(1)
print("\n After fill_diagonal_(1):")
print(tensor)

# Zero out specific elements
tensor.zero_()  # Fill entire tensor with zeros
print("\n After zero_():")
print(tensor)

After fill_(0):
tensor([[-5, -5, -5],
        [-5, -5, -5],
        [-5, -5, -5],
        [-5, -5, -5]])

 After fill_diagonal_(1):
tensor([[ 1, -5, -5],
        [-5,  1, -5],
        [-5, -5,  1],
        [-5, -5, -5]])

 After zero_():
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [19]:
tensor = torch.zeros(3,4)
print("zeros(3,4)\n", tensor)

tensor = torch.ones(3,4)
print("\nones(3,4)\n", tensor)

zeros(3,4)
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

ones(3,4)
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [20]:
# In-place vs out-of-place operations
tensor = torch.tensor([1, 2, 3])

# Out-of-place: creates new tensor (more memory)
new_tensor = tensor + 1

# In-place: modifies existing tensor (less memory)
tensor.add_(1)

print("Same memory?", tensor.data_ptr() == new_tensor.data_ptr())  # False

Same memory? False


In [21]:
import numpy as np

# NumPy to PyTorch with shared memory
numpy_arr = np.array([1, 2, 3, 4, 5])
torch_tensor = torch.from_numpy(numpy_arr)  # Shares memory

print("Original NumPy:", numpy_arr)
print("PyTorch tensor:", torch_tensor)

# Modify NumPy array
numpy_arr[0] = 99
print("\nAfter modifying NumPy:")
print("NumPy array:", numpy_arr)
print("PyTorch tensor:", torch_tensor)  # Also changed!

# Modify PyTorch tensor
torch_tensor[1] = 88
print("\nAfter modifying PyTorch:")
print("NumPy array:", numpy_arr)        # Also changed!
print("PyTorch tensor:", torch_tensor)

Original NumPy: [1 2 3 4 5]
PyTorch tensor: tensor([1, 2, 3, 4, 5])

After modifying NumPy:
NumPy array: [99  2  3  4  5]
PyTorch tensor: tensor([99,  2,  3,  4,  5])

After modifying PyTorch:
NumPy array: [99 88  3  4  5]
PyTorch tensor: tensor([99, 88,  3,  4,  5])


In [22]:
# NumPy to PyTorch with separate memory
numpy_arr = np.array([1, 2, 3, 4, 5])
torch_tensor = torch.tensor(numpy_arr)  # Creates copy

print("Original NumPy:", numpy_arr)
print("PyTorch tensor:", torch_tensor)

# Modify NumPy array
numpy_arr[0] = 99
print("\nAfter modifying NumPy:")
print("NumPy array:", numpy_arr)
print("PyTorch tensor:", torch_tensor)  # Unchanged!

# Modify PyTorch tensor
torch_tensor[1] = 88
print("\nAfter modifying PyTorch:")
print("NumPy array:", numpy_arr)        # Unchanged!
print("PyTorch tensor:", torch_tensor)

Original NumPy: [1 2 3 4 5]
PyTorch tensor: tensor([1, 2, 3, 4, 5])

After modifying NumPy:
NumPy array: [99  2  3  4  5]
PyTorch tensor: tensor([1, 2, 3, 4, 5])

After modifying PyTorch:
NumPy array: [99  2  3  4  5]
PyTorch tensor: tensor([ 1, 88,  3,  4,  5])


In [23]:
# Create a PyTorch tensor
torch_tensor = torch.tensor([[1.0, 2.0, 3.0],
                             [4.0, 5.0, 6.0]])
print("PyTorch tensor:")
print(torch_tensor)
print("Type:", type(torch_tensor))

# Convert to NumPy array
numpy_array = torch_tensor.numpy()
print("\nNumPy array:")
print(numpy_array)
print("Type:", type(numpy_array))
print("Shape:", numpy_array.shape)
print("Dtype:", numpy_array.dtype)

PyTorch tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Type: <class 'torch.Tensor'>

NumPy array:
[[1. 2. 3.]
 [4. 5. 6.]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)
Dtype: float32


In [24]:
import torch

# Original tensor: 3x4
original = torch.tensor([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])
print("Original shape (3x4):", original.shape)
print(original)

# Reshape to 2x3x2
reshaped = original.reshape(2, 3, 2)
print("\nReshaped to (2x3x2):", reshaped.shape)
print(reshaped)

Original shape (3x4): torch.Size([3, 4])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Reshaped to (2x3x2): torch.Size([2, 3, 2])
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])


In [25]:
# Using view() - requires contiguous memory
reshaped_view = original.view(2, 3, 2)
print("Using view() - same result:")
print(reshaped_view.shape)
print(reshaped_view)

Using view() - same result:
torch.Size([2, 3, 2])
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])


In [26]:
# Flatten to 1D
flattened = original.reshape(-1)      # or original.view(-1)
print("Flattened:", flattened.shape)  # torch.Size([12])
print(flattened)  # tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Flatten specific dimensions
flattened_2d = original.reshape(3, -1)      # Keep first dim, flatten rest
print("Flattened 2D:", flattened_2d.shape)  # torch.Size([3, 4])
print(flattened_2d)

Flattened: torch.Size([12])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Flattened 2D: torch.Size([3, 4])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [27]:
print("Original tensor's dim:", original.shape)  # torch.Size([3, 4])
print(original)
# Add new dimensions
with_batch = original.reshape(1, 3, 4)      # Add batch dimension
print("\nWith batch dim:", with_batch.shape)  # torch.Size([1, 3, 4])

# Using unsqueeze()
with_batch2 = original.unsqueeze(0)           # Add dimension at position 0
print("Using unsqueeze:", with_batch2.shape)  # torch.Size([1, 3, 4])
print(with_batch2)

# Remove dimensions of size 1
squeezed = with_batch2.squeeze(0)        # Remove dimension at position 0
print("\nAfter squeeze:", squeezed.shape)  # torch.Size([3, 4])
print("\nAfter squeeze:\n", squeezed)  

Original tensor's dim: torch.Size([3, 4])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

With batch dim: torch.Size([1, 3, 4])
Using unsqueeze: torch.Size([1, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

After squeeze: torch.Size([3, 4])

After squeeze:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [28]:
# Let PyTorch calculate one dimension
original = torch.tensor([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])

# Use -1 for automatic dimension calculation
auto1 = original.reshape(2, -1)    # 2x6
auto2 = original.reshape(-1, 6)    # 2x6
auto3 = original.reshape(2, 3, -1) # 2x3x2

print("2 x -1:", auto1.shape)      # torch.Size([2, 6])
print("-1 x 6:", auto2.shape)      # torch.Size([2, 6])
print("2 x 3 x -1:", auto3.shape)  # torch.Size([2, 3, 2])

2 x -1: torch.Size([2, 6])
-1 x 6: torch.Size([2, 6])
2 x 3 x -1: torch.Size([2, 3, 2])


In [29]:
import torch

# Create individual tensors
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

print("Individual tensors:")
print("tensor1:", tensor1)
print("tensor2:", tensor2)
print("tensor3:", tensor3)

# Stack along a new dimension (default dim=0)
stacked = torch.stack([tensor1, tensor2, tensor3])
print("\nStacked (dim=0):")
print(stacked)
print("\nShape:", stacked.shape)  # torch.Size([3, 3])

Individual tensors:
tensor1: tensor([1, 2, 3])
tensor2: tensor([4, 5, 6])
tensor3: tensor([7, 8, 9])

Stacked (dim=0):
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Shape: torch.Size([3, 3])


In [30]:
# Understanding the difference between stack and cat
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# Concatenate (joins along existing dimension)
concatenated = torch.cat([tensor1, tensor2])
print("Concatenated:", concatenated)              # tensor([1, 2, 3, 4, 5, 6])
print("Concatenated shape:", concatenated.shape)  # torch.Size([6])

# Stack (creates new dimension)
stacked = torch.stack([tensor1, tensor2])
print("\nStacked:\n", stacked)
print("\nStacked shape:", stacked.shape)    # torch.Size([2, 3])

Concatenated: tensor([1, 2, 3, 4, 5, 6])
Concatenated shape: torch.Size([6])

Stacked:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Stacked shape: torch.Size([2, 3])


In [31]:
import torch

matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

print("Original matrix: \n", matrix)
print("\nShape:", matrix.shape)      # torch.Size([2, 3])

# Transpose using .T
transposed = matrix.T
print("\nTransposed (.T): \n", transposed)
print("\nShape:", transposed.shape)  # torch.Size([3, 2])

# Different from reshape
reshaped_matrix = matrix.reshape(3,2)
print(f"\nReshape matrix (3*2) is different from transpose and reshape is:\n {reshaped_matrix} and its shape is: \n {reshaped_matrix.shape}")

Original matrix: 
 tensor([[1, 2, 3],
        [4, 5, 6]])

Shape: torch.Size([2, 3])

Transposed (.T): 
 tensor([[1, 4],
        [2, 5],
        [3, 6]])

Shape: torch.Size([3, 2])

Reshape matrix (3*2) is different from transpose and reshape is:
 tensor([[1, 2],
        [3, 4],
        [5, 6]]) and its shape is: 
 torch.Size([3, 2])


In [32]:
# Alternative for 2D tensors
matrix = torch.tensor([[1, 2], [3, 4]])
transposed_t = matrix.t()
print("Transpose using .t():")
print(transposed_t)

Transpose using .t():
tensor([[1, 3],
        [2, 4]])


In [33]:
# 3D tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]],
                          [[5, 6], [7, 8]]])
print("Original 3D:")
print(tensor_3d)
print("Shape:", tensor_3d.shape)                    # torch.Size([2, 2, 2])

# Transpose specific dimensions
transposed_3d = torch.transpose(tensor_3d, 0, 1)    # Swap dim0 and dim1
print("\nTransposed dim0 and dim1:")
print(transposed_3d)
print("Shape:", transposed_3d.shape)                # torch.Size([2, 2, 2])

# Transpose different dimensions
transposed_3d_2 = torch.transpose(tensor_3d, 1, 2)  # Swap dim1 and dim2
print("\nTransposed dim1 and dim2:")
print(transposed_3d_2)
print("Shape:", transposed_3d_2.shape)              # torch.Size([2, 2, 2])

Original 3D:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])

Transposed dim0 and dim1:
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])

Transposed dim1 and dim2:
tensor([[[1, 3],
         [2, 4]],

        [[5, 7],
         [6, 8]]])
Shape: torch.Size([2, 2, 2])


In [34]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Element-wise operations
add = a + b           # Addition: [5, 7, 9]
subtract = a - b      # Subtraction: [-3, -3, -3]
multiply = a * b      # Multiplication: [4, 10, 18]
divide = a / b        # Division: [0.25, 0.4, 0.5]
power = a ** b        # Power: [1, 32, 729]
modulo = a % 2        # Modulo: [1, 0, 1]

print("First tensor: ", a)
print("Second tensor: ", b)

print("\nAdd: ", add)
print("Subtract: ", subtract)
print("Multiply: ", multiply)
print("Divide: ", divide)
print("Power: ", power)
print("Modulo: ", modulo)


# Equivalent function forms
add_func = torch.add(a, b)
sub_func = torch.sub(a, b)
mul_func = torch.mul(a, b)
div_func = torch.div(a, b)

First tensor:  tensor([1, 2, 3])
Second tensor:  tensor([4, 5, 6])

Add:  tensor([5, 7, 9])
Subtract:  tensor([-3, -3, -3])
Multiply:  tensor([ 4, 10, 18])
Divide:  tensor([0.2500, 0.4000, 0.5000])
Power:  tensor([  1,  32, 729])
Modulo:  tensor([1, 0, 1])


In [35]:
x = torch.tensor([1.0, 2.0, 3.0])

# In-place operations (modify original tensor)
x.add_(1)            # x = x + 1 → [2., 3., 4.]
x.sub_(0.5)          # x = x - 0.5 → [1.5, 2.5, 3.5]
x.mul_(2)            # x = x * 2 → [3., 5., 7.]
x.div_(2)            # x = x / 2 → [1.5, 2.5, 3.5]
x.pow_(2)            # x = x² → [2.25, 6.25, 12.25]

tensor([ 2.2500,  6.2500, 12.2500])

In [36]:
# Matrix multiplication - Using @
A = torch.tensor([[1, 2], [3, 4], [5, 6]])             # 3*2
B = torch.tensor([[7, 8, 9, 10], [11, 12, 13, 14]])   # 2*4

# Matrix multiplication
matmul = A @ B                                        # Result: 3*4

print("Matrix A: \n", A)
print("\nMatrix B: \n", B)
print("\n Matrix multiplication A and B: \n", matmul)

Matrix A: 
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

Matrix B: 
 tensor([[ 7,  8,  9, 10],
        [11, 12, 13, 14]])

 Matrix multiplication A and B: 
 tensor([[ 29,  32,  35,  38],
        [ 65,  72,  79,  86],
        [101, 112, 123, 134]])


In [37]:
# Matrix multiplication - Using torch.matmul(A, B)

A = torch.tensor([[1, 2], [3, 4], [5, 6]])            # 3*2
B = torch.tensor([[7, 8, 9, 10], [11, 12, 13, 14]])   # 2*4

# Matrix multiplication
matmul = torch.matmul(A, B)                           # Result: 3*4 

print("Matrix A: \n", A)
print("\nMatrix B: \n", B)
print("\n Matrix multiplication A and B: \n", matmul)

Matrix A: 
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

Matrix B: 
 tensor([[ 7,  8,  9, 10],
        [11, 12, 13, 14]])

 Matrix multiplication A and B: 
 tensor([[ 29,  32,  35,  38],
        [ 65,  72,  79,  86],
        [101, 112, 123, 134]])


In [38]:
# Matrix Dot product
vector1 = torch.tensor([1, 2, 3])
vector2 = torch.tensor([4, 5, 6])

dot_product = torch.dot(vector1, vector2)  # 1*4 + 2*5 + 3*6 = 32

print("Vector A: \n", vector1)
print("\nVector B: \n", vector2)
print("\nDot product \n", dot_product)

Vector A: 
 tensor([1, 2, 3])

Vector B: 
 tensor([4, 5, 6])

Dot product 
 tensor(32)


In [39]:
# Batch matrix multiplication
batch_A = torch.randn(3, 2, 4)    # 3 batches of 2x4 matrices
batch_B = torch.randn(3, 4, 3)    # 3 batches of 4x3 matrices
batch_matmul = torch.bmm(batch_A, batch_B)  # 3x2x3 result

print("Shape batch A: \n", batch_A.shape)
print("\nShape batch B: \n", batch_B.shape)
print("\nShape batch matmul: \n", batch_matmul.shape)

Shape batch A: 
 torch.Size([3, 2, 4])

Shape batch B: 
 torch.Size([3, 4, 3])

Shape batch matmul: 
 torch.Size([3, 2, 3])


In [40]:
tensor = torch.tensor([[1., 2., 3.], 
                       [4., 5., 6.]])

# Sum operations
sum_all = tensor.sum()            # 21
sum_dim0 = tensor.sum(dim=0)      # [5, 7, 9] (sum along rows)
sum_dim1 = tensor.sum(dim=1)      # [6, 15] (sum along columns)

# Mean operations
mean_all = tensor.mean()          # 3.5
mean_dim0 = tensor.mean(dim=0)    # [2.5, 3.5, 4.5]

# Min/Max operations
max_val, max_idx = tensor.max(dim=1)  # (values: [3,6], indices: [2,2])
min_val = tensor.min()            # 1

# Other reductions
prod = tensor.prod()              # Product: 720
std = tensor.std()                # Standard deviation
var = tensor.var()                # Variance

print("sum_all: ", sum_all)
print("sum_dim0: ", sum_dim0)
print("sum_dim1: ", sum_dim1)
print("mean_all: ", mean_all)
print("mean_dim0: ", mean_dim0)
print("max_val: ", mean_all, " And max_idx", max_idx)
print("min_val: ", min_val)
print("prod: ", prod)
print("Standard deviation: ", std)
print("Variance: ", var)

sum_all:  tensor(21.)
sum_dim0:  tensor([5., 7., 9.])
sum_dim1:  tensor([ 6., 15.])
mean_all:  tensor(3.5000)
mean_dim0:  tensor([2.5000, 3.5000, 4.5000])
max_val:  tensor(3.5000)  And max_idx tensor([2, 2])
min_val:  tensor(1.)
prod:  tensor(720.)
Standard deviation:  tensor(1.8708)
Variance:  tensor(3.5000)


In [41]:
angles = torch.tensor([0, torch.pi/4, torch.pi/2])

# Basic trig functions
sin_val = torch.sin(angles)       # [0., 0.7071, 1.]
cos_val = torch.cos(angles)       # [1., 0.7071, 0.]
tan_val = torch.tensor([0, 1, 2])
atan_val = torch.atan(tan_val)    # Inverse tangent

# Hyperbolic functions
sinh_val = torch.sinh(angles)
cosh_val = torch.cosh(angles)

print("sin", sin_val)
print("cos", cos_val)
print("tan", tan_val)
print("atan", atan_val)
print("sinh", sinh_val)
print("cosh", sinh_val)

sin tensor([0.0000, 0.7071, 1.0000])
cos tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08])
tan tensor([0, 1, 2])
atan tensor([0.0000, 0.7854, 1.1071])
sinh tensor([0.0000, 0.8687, 2.3013])
cosh tensor([0.0000, 0.8687, 2.3013])


In [42]:
x = torch.tensor([1.0, 2.0, 3.0])

# Exponential functions
exp = torch.exp(x)                # e^x: [2.718, 7.389, 20.085]
exp2 = torch.exp2(x)              # 2^x: [2., 4., 8.]
pow = torch.pow(x, 2)             # x²: [1., 4., 9.]

# Logarithmic functions
log = torch.log(x)                # Natural log: [0., 0.693, 1.099]
log10 = torch.log10(x)            # Base-10 log: [0., 0.301, 0.477]
log2 = torch.log2(x)              # Base-2 log: [0., 1., 1.585]

# Special functions
sqrt = torch.sqrt(x)              # Square root: [1., 1.414, 1.732]
rsqrt = torch.rsqrt(x)            # Reciprocal square root

print("e^x:", exp)
print("2^x:", exp2)
print("x²:", pow)
print("Natural log:", log)
print("Base-10 log:", log10)
print("Base-2 log:", log2)
print("Square root:", sqrt)
print("Reciprocal square root:", rsqrt)

e^x: tensor([ 2.7183,  7.3891, 20.0855])
2^x: tensor([2., 4., 8.])
x²: tensor([1., 4., 9.])
Natural log: tensor([0.0000, 0.6931, 1.0986])
Base-10 log: tensor([0.0000, 0.3010, 0.4771])
Base-2 log: tensor([0.0000, 1.0000, 1.5850])
Square root: tensor([1.0000, 1.4142, 1.7321])
Reciprocal square root: tensor([1.0000, 0.7071, 0.5774])


In [43]:
x = torch.tensor([1.4, 2.6, -1.7, 3.0])

# Rounding operations
floor = torch.floor(x)            # [1., 2., -2., 3.]
ceil = torch.ceil(x)              # [2., 3., -1., 3.]
round_val = torch.round(x)        # [1., 3., -2., 3.]
trunc = torch.trunc(x)            # [1., 2., -1., 3.]

print("floor: ", floor)
print("ceil: ", ceil)
print("round_val: ", round_val)
print("trunc: ", trunc)

floor:  tensor([ 1.,  2., -2.,  3.])
ceil:  tensor([ 2.,  3., -1.,  3.])
round_val:  tensor([ 1.,  3., -2.,  3.])
trunc:  tensor([ 1.,  2., -1.,  3.])


In [44]:
# Comparison operations
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 2, 2])

equal = a == b                    # [False, True, False]
not_equal = a != b                # [True, False, True]
greater = a > b                   # [False, False, True]
less = a < b                      # [True, False, False]

# All/any operations
all_true = torch.all(a > 0)       # True (all elements > 0)
any_true = torch.any(a > 2)       # True (at least one element > 2)

print("equal: ", equal)
print("not_equal: ", not_equal)
print("greater: ", greater)
print("less: ", less)
print("True (all elements > 0): ", all_true)
print("True (at least one element > 2): ", any_true)

equal:  tensor([False,  True, False])
not_equal:  tensor([ True, False,  True])
greater:  tensor([False, False,  True])
less:  tensor([ True, False, False])
True (all elements > 0):  tensor(True)
True (at least one element > 2):  tensor(True)


In [45]:
tensor = torch.tensor([[1, 0, 12], 
                       [4, 3, 9], 
                       [2, 7, 6]])

# Statistical functions
mean = torch.mean(tensor.float(), dim=1) # 5.0
median = torch.median(tensor)     # 5
std = torch.std(tensor.float())   # Standard deviation
var = torch.var(tensor.float())   # Variance

# Sorting
sorted_vals, sorted_indices = torch.sort(tensor, dim=1)

# Top-k elements
topk_vals, topk_indices = torch.topk(tensor, k=2, dim=1)

print("Original tensor: \n", tensor)
print("mean: ", mean)
print("median: ", median)
print("Standard deviation: ", std)
print("Variance: ", var)
print("sorted_vals: \n", sorted_vals, "\nsorted_indices: \n", sorted_indices)
print("topk_vals: \n", topk_vals, "\ntopk_indices\n", topk_indices)


Original tensor: 
 tensor([[ 1,  0, 12],
        [ 4,  3,  9],
        [ 2,  7,  6]])
mean:  tensor([4.3333, 5.3333, 5.0000])
median:  tensor(4)
Standard deviation:  tensor(3.9511)
Variance:  tensor(15.6111)
sorted_vals: 
 tensor([[ 0,  1, 12],
        [ 3,  4,  9],
        [ 2,  6,  7]]) 
sorted_indices: 
 tensor([[1, 0, 2],
        [1, 0, 2],
        [0, 2, 1]])
topk_vals: 
 tensor([[12,  1],
        [ 9,  4],
        [ 7,  6]]) 
topk_indices
 tensor([[2, 0],
        [2, 0],
        [1, 2]])


In [46]:
x = torch.tensor([-2, -1, 0, 1, 2, 3, 4])

# Clamping values
clamped_min = torch.clamp(x, min=0)    # [0, 0, 0, 1, 2, 3, 4]
clamped_max = torch.clamp(x, max=2)    # [-2, -1, 0, 1, 2, 2, 2]
clamped_range = torch.clamp(x, min=0, max=3)   # [0, 0, 0, 1, 2, 3, 3]

# Absolute value
abs_val = torch.abs(x)

# Sign function
sign = torch.sign(x)   # [-1, 0, 1]

print("Original vector: ", x)
print("clamped_min: ", clamped_min)
print("clamped_max: ", clamped_max)
print("clamped_range: ", clamped_range)
print("abs_val: ", abs_val)
print("sign: ", sign)

Original vector:  tensor([-2, -1,  0,  1,  2,  3,  4])
clamped_min:  tensor([0, 0, 0, 1, 2, 3, 4])
clamped_max:  tensor([-2, -1,  0,  1,  2,  2,  2])
clamped_range:  tensor([0, 0, 0, 1, 2, 3, 3])
abs_val:  tensor([2, 1, 0, 1, 2, 3, 4])
sign:  tensor([-1, -1,  0,  1,  1,  1,  1])


In [47]:
# Broadcasting allows operations between different shaped tensors
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])  # 2x3

vector = torch.tensor([10, 20, 30]) # 3

# Broadcasting: vector is expanded to match matrix shape
result = matrix + vector          # [[11, 22, 33], [14, 25, 36]]

# Scalar broadcasting
scalar_result = matrix * 2        # [[2, 4, 6], [8, 10, 12]]

print("Broadcasting allows operations between different shaped tensors")
print("Original matrix: \n", matrix)
print("Original vector: \n", vector)

print("\nBroadcasting (matrix + vector): \n", result)
print("\nScalar broadcasting (matrix * 2 ): \n", scalar_result)


Broadcasting allows operations between different shaped tensors
Original matrix: 
 tensor([[1, 2, 3],
        [4, 5, 6]])
Original vector: 
 tensor([10, 20, 30])

Broadcasting (matrix + vector): 
 tensor([[11, 22, 33],
        [14, 25, 36]])

Scalar broadcasting (matrix * 2 ): 
 tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [48]:
import torch

# Create a tensor
tensor = torch.tensor([-1, 0, 1, 2, 3, 4])
print("Original:", tensor, tensor.dtype)  # torch.int64

# Method 1: Using .to() method (recommended)
float_tensor = tensor.to(torch.float32)
double_tensor = tensor.to(torch.float64)
half_tensor = tensor.to(torch.float16)

print("to(float32):", float_tensor.dtype)    # torch.float32
print("to(float64):", double_tensor.dtype)   # torch.float64
print("to(float16):", half_tensor.dtype)     # torch.float16

# Method 2: Using type-specific methods
float_tensor2 = tensor.float()      # Convert to float32
double_tensor2 = tensor.double()    # Convert to float64
half_tensor2 = tensor.half()        # Convert to float16
int_tensor = tensor.int()           # Convert to int32
long_tensor = tensor.long()         # Convert to int64
float_to_bool = float_tensor.bool()      # non-zero → True)

print(".float():", float_tensor2.dtype)   # torch.float32
print(".int():", int_tensor.dtype)        # torch.int32
print(".float_to_bool: ", float_to_bool)

Original: tensor([-1,  0,  1,  2,  3,  4]) torch.int64
to(float32): torch.float32
to(float64): torch.float64
to(float16): torch.float16
.float(): torch.float32
.int(): torch.int32
.float_to_bool:  tensor([ True, False,  True,  True,  True,  True])


In [49]:
import torch
import numpy as np

# Convert with specific dtype
original = torch.tensor([1, 2, 3])
casted = torch.as_tensor(original, dtype=torch.float32)

print("Original:", original.dtype)  # torch.int64
print("Casted:", casted.dtype)      # torch.float32

# Works with various data sources
from_numpy = torch.as_tensor(np.array([1, 2, 3]), dtype=torch.float64)
from_list = torch.as_tensor([1.5, 2.5], dtype=torch.int32)

print("From numpy:", from_numpy.dtype)  # torch.float64
print("From list:", from_list.dtype)    # torch.int32 (truncates to [1, 2])

Original: torch.int64
Casted: torch.float32
From numpy: torch.float64
From list: torch.int32


In [50]:
import torch

# Uniform distribution [0, 1)
uniform = torch.rand(2, 3)     # 2x3 tensor with values between 0 and 1
print("Uniform [0,1):")
print(uniform)
print("Shape:", uniform.shape)

Uniform [0,1):
tensor([[0.1763, 0.6581, 0.2397],
        [0.1151, 0.1782, 0.9220]])
Shape: torch.Size([2, 3])


In [51]:
import torch

# Normal distribution (mean=0, std=1)
normal = torch.randn(2, 3)  # 2x3 tensor from normal distribution
print("\nNormal (0,1):")
print(normal)


Normal (0,1):
tensor([[-0.5371,  0.1921,  0.6908],
        [-0.6642,  0.5165,  0.9785]])


In [52]:
import torch

# Integer random values
integers = torch.randint(0, 10, (2, 3))  # 2x3 tensor, values 0-9
print("\nIntegers [0,10):")
print(integers)


Integers [0,10):
tensor([[2, 7, 7],
        [5, 2, 5]])


In [53]:
# Specific range uniform
rand_range = torch.FloatTensor(3, 3).uniform_(-5, 5)  # Uniform [-5, 5]
print("\nUniform [-5,5]:\n", rand_range)


Uniform [-5,5]:
 tensor([[-2.4747,  2.4348, -0.7725],
        [-1.5818, -3.6857, -0.9675],
        [-1.5719,  1.4331,  1.6299]])


In [54]:
# Gamma distribution
gamma = torch.distributions.Gamma(2.0, 1.0).sample((3,))
print("Gamma samples:", gamma)

# Beta distribution
beta = torch.distributions.Beta(2.0, 5.0).sample((3,))
print("Beta samples:", beta)

# Poisson distribution
poisson = torch.poisson(torch.tensor([1.0, 2.0, 3.0]))
print("Poisson samples:", poisson)

# Exponential distribution
exponential = torch.distributions.Exponential(1.0).sample((3,))
print("Exponential samples:", exponential)

Gamma samples: tensor([0.7633, 0.8111, 3.3717])
Beta samples: tensor([0.1985, 0.7042, 0.3983])
Poisson samples: tensor([1., 5., 1.])
Exponential samples: tensor([0.4401, 0.0113, 3.2566])


In [55]:
# Set seed for reproducible results
torch.manual_seed(42)

# These will be the same every time
random1 = torch.rand(2, 2)
random2 = torch.randn(2, 2)

print("With seed 42:")
print("Random 1:\n", random1)
print("Random 2:\n", random2)

# Reset seed for different results
torch.manual_seed(123)
different_random = torch.rand(2, 2)
print("\nWith seed 123:\n", different_random)

With seed 42:
Random 1:
 tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
Random 2:
 tensor([[ 0.2345,  0.2303],
        [-1.1229, -0.1863]])

With seed 123:
 tensor([[0.2961, 0.5166],
        [0.2517, 0.6886]])


In [56]:
# Create a tensor
tensor = torch.zeros(3, 3)

# Fill with random values in-place
tensor.uniform_()           # Fill with uniform [0,1)
print("After uniform_():\n", tensor)

tensor.normal_()            # Fill with normal (0,1)
print("\nAfter normal_():\n", tensor)

tensor.bernoulli_(0.5)      # Fill with Bernoulli (p=0.5)
print("\nAfter bernoulli_(0.5):\n", tensor)

# Specific range
tensor.uniform_(-1, 1)      # Fill with uniform [-1,1)
print("\nAfter uniform_(-1,1):\n", tensor)

After uniform_():
 tensor([[0.0740, 0.8665, 0.1366],
        [0.1025, 0.1841, 0.7264],
        [0.3153, 0.6871, 0.0756]])

After normal_():
 tensor([[-0.6219, -0.3076, -0.5987],
        [-0.5564, -0.0596, -1.9858],
        [-0.2109,  1.9667, -0.8350]])

After bernoulli_(0.5):
 tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 0.]])

After uniform_(-1,1):
 tensor([[ 0.8313, -0.1320, -0.8457],
        [-0.2869, -0.7043,  0.0661],
        [-0.1867, -0.5364, -0.0909]])


In [57]:
import torch
import numpy as np

# Set seed for CPU operations
torch.manual_seed(42)

# Generate random tensors
random1 = torch.rand(2, 3)
random2 = torch.randn(2, 3)

print("With seed 42:")
print("Random 1:\n", random1)
print("Random 2:\n", random2)

# Reset seed to get same sequence
torch.manual_seed(42)
random1_again = torch.rand(2, 3)
random2_again = torch.randn(2, 3)

print("\nSame seed again:")
print("Random 1 again:\n", random1_again)
print("Random 2 again:\n", random2_again)

print("\nAre they equal?")
print("Random1:", torch.equal(random1, random1_again))
print("Random2:", torch.equal(random2, random2_again))

With seed 42:
Random 1:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
Random 2:
 tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])

Same seed again:
Random 1 again:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
Random 2 again:
 tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])

Are they equal?
Random1: True
Random2: True


In [58]:
# Set seed for GPU operations
if torch.cuda.is_available():
    torch.cuda.manual_seed(42)
    torch.cuda.manual_seed_all(42)  # For multi-GPU
    
    # Generate random tensors on GPU
    gpu_random = torch.rand(2, 3, device='cuda')
    print("GPU random tensor:\n", gpu_random.cpu())  # Move to CPU for printing

In [59]:
import torch

# Set PyTorch seed to 123
torch.manual_seed(123)

# Generate reproducible random tensors
random_tensor = torch.rand(3, 3)
random_normal = torch.randn(5)
random_ints = torch.randint(0, 10, (5,))

print("PyTorch with seed 123:")
print("Random tensor:\n", random_tensor)
print("Random normal:", random_normal)
print("Random integers:", random_ints)

PyTorch with seed 123:
Random tensor:
 tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841]])
Random normal: tensor([ 0.4422, -1.0854, -0.6219, -0.3076, -0.5987])
Random integers: tensor([6, 5, 7, 9, 2])


In [60]:
import torch

# 1D tensor
tensor_1d = torch.tensor([3, 1, 4, 1, 5, 9, 2])
max_index = torch.argmax(tensor_1d)
print("1D tensor:", tensor_1d)
print("argmax:", max_index.item())  
print("Max value:", tensor_1d[max_index].item())

1D tensor: tensor([3, 1, 4, 1, 5, 9, 2])
argmax: 5
Max value: 9


In [61]:
# 2D tensor
tensor_2d = torch.tensor([
    [1, 5, 3],
    [4, 2, 6], 
    [7, 8, 0]
])
print("2D tensor:\n", tensor_2d)

# Default: flatten and find global maximum
global_max = torch.argmax(tensor_2d)
print("Global argmax (flattened):", global_max.item())  

# Along rows (dim=0) - find max in each column
max_per_column = torch.argmax(tensor_2d, dim=0)
print("argmax along dim=0 (columns):", max_per_column)  

# Along columns (dim=1) - find max in each row  
max_per_row = torch.argmax(tensor_2d, dim=1)
print("argmax along dim=1 (rows):", max_per_row) 

2D tensor:
 tensor([[1, 5, 3],
        [4, 2, 6],
        [7, 8, 0]])
Global argmax (flattened): 7
argmax along dim=0 (columns): tensor([2, 2, 1])
argmax along dim=1 (rows): tensor([1, 2, 1])


In [62]:
import torch

# 1D tensor
tensor_1d = torch.tensor([3, 1, 4, 1, 5, 9, 2])
min_index = torch.argmin(tensor_1d)
print("1D tensor:", tensor_1d)
print("argmin:", min_index.item())  
print("Min value:", tensor_1d[min_index].item())

1D tensor: tensor([3, 1, 4, 1, 5, 9, 2])
argmin: 1
Min value: 1


In [63]:
# 2D tensor
tensor_2d = torch.tensor([
    [5, 1, 3],
    [4, 2, 6], 
    [7, 8, 0]
])
print("2D tensor:\n", tensor_2d)

# Default: flatten and find global maximum
global_min = torch.argmin(tensor_2d)
print("Global argmin (flattened):", global_min.item())  

# Along rows (dim=0) - find max in each column
min_per_column = torch.argmin(tensor_2d, dim=0)
print("argmin along dim=0 (columns):", min_per_column)  

# Along columns (dim=1) - find max in each row  
min_per_row = torch.argmin(tensor_2d, dim=1)
print("argmin along dim=1 (rows):", min_per_row) 

2D tensor:
 tensor([[5, 1, 3],
        [4, 2, 6],
        [7, 8, 0]])
Global argmin (flattened): 8
argmin along dim=0 (columns): tensor([1, 0, 2])
argmin along dim=1 (rows): tensor([1, 1, 2])


In [64]:
import torch
import torch.nn.functional as F

# Multiple labels
labels = torch.tensor([0, 2, 1, 3])
one_hot_batch = F.one_hot(labels, num_classes=4)
print("\nLabels:", labels)
print("One-hot batch:\n", one_hot_batch)


Labels: tensor([0, 2, 1, 3])
One-hot batch:
 tensor([[1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1]])


In [65]:
# 2D tensor of labels
labels_2d = torch.tensor([[0, 1], 
                          [2, 0],
                          [1, 2]])
print("2D labels:\n", labels_2d)

# One-hot encoding adds a new dimension
one_hot_2d = F.one_hot(labels_2d, num_classes=3)
print("\n2D one-hot shape:", one_hot_2d.shape)  # torch.Size([3, 2, 3])
print("2D one-hot:\n", one_hot_2d)

2D labels:
 tensor([[0, 1],
        [2, 0],
        [1, 2]])

2D one-hot shape: torch.Size([3, 2, 3])
2D one-hot:
 tensor([[[1, 0, 0],
         [0, 1, 0]],

        [[0, 0, 1],
         [1, 0, 0]],

        [[0, 1, 0],
         [0, 0, 1]]])
